language: node_js

before_install:
        - npm i -g vuepress
node_js:
        - "node"
script: "docs:build"
deploy:
  provider: pages
  project-name: "Segment Routing"
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master
  local-dir: ".vuepress/dist"

