title: 'ChallProj'
description: 'Segment Routing'
base: '/segmentRouting/'

themeConfig:
    sidebar:
        - title: 'Main Part'
          collapsilbe: false
          children:
            - '/'
            - '/content/xml_api'
            - '/content/net_conf'
            - '/content/rest_conf'
            - '/content/yang'
        
        - title: 'Appendix'
          collapsilbe: true
          children:
            - 'appendix/links'
